#!/usr/bin/python
##
## EPITECH PROJECT, 2021
## 105torus
## File description:
## main 105torus file 
##

from fold.math_calc import *
from fold.methods.bisection_method.bisection import *
from fold.methods.newton_method.newton import *
from fold.methods.secant_method.secant import *
from fold.bootstrap.yo import *
from fold.error_handling import error_handling
from sys import argv

def choseMethod(argv):
    if argv[1] == "1":
        bisectionMethod()
    elif argv[1] == "2":
        newtonMethod()
    elif (argv[1] == "3"):
        secantMethod()


def main():
    if (error_handling() == 84):
        exit (84)
    else:
        choseMethod(argv)


main()