def helpfile():
    print ("USAGE")
    print ("\t./105torus opt a0 a1 a2 a3 a4 n")
    print ("DESCRIPTON")
    print ("\topt\tmethode option:")
    print ("\t\t\t1 for the bisection method")
    print ("\t\t\t2 for the Newton's method")
    print ("\t\t\t3 for the secant method")
    print ("\ta[0-4]\tcoefficients of the equation")
    print ("\tn\tprecision (the application of the polynomial to the solution should")
    print ("\t\tbe smaller than 10^-n")