#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## 110borwein
## File description:
## main function's project
##

from sys import argv
from handling.error_handling import errorHandling
from borwein.borwein import borwein

def main():
    if errorHandling() == 84:
        exit (84)
    borwein(argv)
    exit (0)

if __name__ == "__main__":
    main()